---
- hosts: default
  gather_facts: false
  vars:
    env:
      PATH: "{{ ansible_env.PATH }}:/usr/local/phpenv/shims"
 

  pre_tasks:
      - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      - setup: # aka gather_facts

  tasks:
    - include_vars: "group_vars/vhosts.yml"

  roles:
   #- common
   #- phpenv
   - waldenit.nginx 
   #- waldenit.mysql
   - waldenit.apache2
   #- waldenit.wordpress
   #- firewall
