#- include_vars: 'group_vars/vhosts.yml'

- name: reconfigure apache port
  lineinfile:
    dest: /etc/apache2/ports.conf
    state: present
    regexp: '^Listen '
    line: 'Listen {{apache_port}}'

- name: enable modules
  command: a2enmod proxy_fcgi

- name: enable modules
  command: a2enmod rewrite

- service:
    name: apache2
    state: restarted
