- lineinfile:
    dest: '/etc/default/locale'
    regexp: '^LC_ALL='
    line: 'LC_ALL=en_US.UTF-8'

- apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: upgrade apt packages
  apt: upgrade=yes

- name: install dependencies
  apt: 
    name: "{{item}}"
    state: present
  with_items:
    - python-pip

- name: swap space
  shell: |
    dd if=/dev/zero of=/newswap bs=1024 count=262144
    mkswap /newswap
    chmod 0600 /newswap
    swapon /newswap
