- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600


- name: install letsencrypt
  apt: 
    name: "{{item}}"
    state: present
  with_items:
    - letsencrypt

- name: ini file
    template: 
      src: webroot.ini.j2
      dest: /etc/letsencrypt.ini
    with_indexed_items: vhosts.values()|list
    when: item.1.ssl_enabled is true

