---
- include: "system/install_versions.yml"
  when: "phpenv_env == 'system'"

- include: "user/install_versions.yml"
  when: "phpenv_env == 'user'"

- name: link to /usr/bin
  file:
    src: /usr/local/phpenv/shims/php
    dest: /usr/bin/php
    state: link


